version: '3.8'

services:
  backend:
    build:
      context: ../app/backend
      dockerfile: Dockerfile
    container_name: carbonpay-backend
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
    env_file:
      - ../.env
    networks:
      - carbonpay-network
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-3000}/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:13
    container_name: carbonpay-postgres
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: carbonpay
      POSTGRES_PASSWORD: carbonpay
      POSTGRES_DB: carbonpay
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carbonpay-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U carbonpay -d carbonpay'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${PORT:-3001}:${PORT:-3001}"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ../client:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: npm start

networks:
  carbonpay-network:
    driver: bridge

volumes:
  postgres_data:
