version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carbonpay-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    networks:
      - carbonpay-network
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: carbonpay
      POSTGRES_PASSWORD: carbonpay
      POSTGRES_DB: carbonpay
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database:/docker-entrypoint-initdb.d
  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${PORT:-3001}:${PORT:-3001}"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ../client:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: npm start

networks:
  carbonpay-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 